#!/bin/sh   

### BEGIN INIT INFO 
# Provides: pure-ftpd  
# Required-Start: $all 
# Required-Stop: $all  
# Default-Start: 2 3 4 5   
# Default-Stop: 0 1 6  
# Short-Description: starts pure-ftpd server 
# Description: starts pure-ftpd server    
### END INIT INFO  


DAEMON=/sbin/pure-config.pl
LOGFILE=/var/log/pureftpd.log
NAME="pure-ftpd"
PATH=/usr/local/sbin:$PATH
CONFIGFILE=/etc/pure-ftpd.conf
PIDFILE=/var/run/pure-ftpd.pid

test -x $DAEMON || exit 0

case "$1" in
  start)
    echo  "Starting $NAME. "
    exec start-stop-daemon --start --pidfile "$PIDFILE" --exec  $DAEMON -- $CONFIGFILE -A -B
    ;;
  stop)
    echo  "Stopping $NAME. "
    exec start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
    ;;
  restart|force-reload)
    echo  "Restarting $NAME. "
    exec start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
    sleep 1
    exec start-stop-daemon --start --pidfile "$PIDFILE" --exec  $DAEMON -- $CONFIGILE -A -B
    ;;
  reload)
  echo "Reloading $NAME configuration: "
  exec start-stop-daemon --stop --signal HUP --quiet --pidfile "$PIDFILE" --exec $DAEMON -- $CONFIGFILE -A -B
  ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
